<?php
/**
 * ****************************************************************************
 *  - TDMPicture By TDM   - TEAM DEV MODULE FOR XOOPS
 *  - Licence PRO Copyright (c)  (http://www.tdmxoops.net)
 *
 * Cette licence, contient des limitations!!!
 *
 * 1. Vous devez poss�der une permission d'ex�cuter le logiciel, pour n'importe quel usage.
 * 2. Vous ne devez pas l' �tudier,
 * 3. Vous ne devez pas le redistribuer ni en faire des copies,
 * 4. Vous n'avez pas la libert� de l'am�liorer et de rendre publiques les modifications
 *
 * @license     TDMFR PRO license
 * @author		TDMFR ; TEAM DEV MODULE 
 *
 * ****************************************************************************
 */
 
if (!defined('XOOPS_ROOT_PATH')) {
	die('XOOPS root path not defined');
}

$mydirname = basename( dirname( __FILE__ ) ) ;

$modversion['name'] = "TDMPicture";
$modversion['version'] = 1.07;
$modversion['description'] = 'Image manager';
$modversion['credits'] = "";
$modversion['author'] = 'TDM, Venom';
$modversion['pseudo']  = 'Venom';
$modversion['website']  = '';
$modversion['name_website'] = '';
$modversion['license'] = "GPL see LICENSE";
$modversion['help']             = 'page=help';
$modversion['official'] = 1;
$modversion['image'] = "images/TDMPicture_logo.png";
$modversion['dirname'] = basename(dirname(__FILE__));

$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16']        = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32']        = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion['status_version']   = 'Final';
$modversion['release_date']     = '2013/09/01';
//$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['onInstall']        = 'include/install.php';
//$modversion['onUpdate']         = 'include/update.php';
$modversion['min_php']          = '5.2';
$modversion['min_xoops']        = "2.5.6";

// Sql file
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

//update
$modversion['onUpdate'] = 'include/update.php';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "tdmpicture_file";
$modversion['tables'][1] = "tdmpicture_cat";
$modversion['tables'][2] = "tdmpicture_pl";
$modversion['tables'][3] = "tdmpicture_vote";



// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]['file'] = 'tdmpicture_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'tdmpicture_viewcat.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][5]['file'] = 'tdmpicture_tpfile.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'tdmpicture_tplecteur.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'tdmpicture_tpplaylist.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'tdmpicture_viewfile.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][10]['file'] = 'tdmpicture_modfile.html';
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = 'tdmpicture_liste.html';
$modversion['templates'][11]['description'] = '';
$modversion['templates'][12]['file'] = 'tdmpicture_rss.html';
$modversion['templates'][12]['description'] = 'RSS';

// Menu
$modversion['hasMain'] = 1;
//perm

global $xoopsUser;
$gperm_handler =& xoops_gethandler('groupperm');
$module_handler =& xoops_gethandler('module');
$xoopsModule =& $module_handler->getByDirname($modversion['dirname']);

//permission
if (is_object($xoopsUser)) {
    $groups = $xoopsUser->getGroups();
	 $uid = $xoopsUser->getVar('uid');
} else {
	$groups = XOOPS_GROUP_ANONYMOUS;
	$uid = false;
}

if ($xoopsModule) {
//perm
if ($gperm_handler->checkRight('tdmpicture_view', 8, $groups, $xoopsModule->getVar('mid'))) {
$modversion['sub'][1]['name'] = _MI_TDMPICTURE_UPLOAD;
$modversion['sub'][1]['url'] = "submit.php";
}

if ($gperm_handler->checkRight('tdmpicture_view', 1024, $groups, $xoopsModule->getVar('mid'))) {
$modversion['sub'][2]['name'] = _MI_TDMPICTURE_CAT;
$modversion['sub'][2]['url'] = "submit.php?op=cat";
}

if($uid) {
$modversion['sub'][3]['name'] = _MI_TDMPICTURE_VIEWMYALBUM;
$modversion['sub'][3]['url'] = "user.php?ut=".$uid;
}
}

$modversion['sub'][5]['name'] = _MI_TDMPICTURE_VIEWALBUM;
$modversion['sub'][5]['url'] = "search.php";


//recherche
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "tdmpicture_search";

// Notification
$modversion['hasNotification'] = 0;

$modversion['dirname'];

$i=1;
$modversion['config'][$i]['name'] = 'tdm_upload_path';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_UPLOAD_PATH';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_UPLOAD_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/modules/'.$modversion['dirname'].'/upload/';
$i++;
$modversion['config'][$i]['name'] = 'tdm_upload_thumb';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_UPLOAD_THUMB';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_UPLOAD_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/modules/'.$modversion['dirname'].'/upload/thumb/';
$i++;

$modversion['config'][$i]['name'] = 'tdm_myalbum_path';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_MYALBUM_PATH';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_UPLOAD_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/uploads/photos/';
$i++;
$modversion['config'][$i]['name'] = 'tdm_myalbum_thumb';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_MYALBUM_THUMB';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_UPLOAD_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/uploads/thumbs/';
$i++;

$modversion['config'][$i]['name'] = 'tdm_extgallery_path';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_EXTGALLERY_PATH';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_UPLOAD_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/uploads/extgallery/public-photo/medium/';
$i++;
$modversion['config'][$i]['name'] = 'tdm_extgallery_thumb';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_EXTGALLERY_THUMB';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_UPLOAD_DESC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '/uploads/extgallery/public-photo/thumb/';
$i++;

$modversion['config'][$i]['name'] = 'tdmpicture_mimemax';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_MIMEMAX';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '10485760';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_upmax';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_UPMAX';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '5';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_mimetype';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_MIMETYPE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'image/png|image/bmp|image/gif|image/ief|image/jpeg|image/pipeg|image/tiff|image/x-portable-anymap|image/x-portable-bitmap|image/x-portable-graymap|image/x-portable-pixmap|image/x-rgb|image/x-xbitmap|image/x-xwindowdump';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_size';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_SIZE';
$modversion['config'][$i]['description'] = '_MI_TDMPICTURE_SIZEDESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '100x75|150x112|320x240|640x480|800x600|1024x768|1280x1024|1600x1200';
$i++;
//$modversion['config'][$i]['name'] = 'tdmpicture_java_width';
//$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_JAVA_WIDTH';
//$modversion['config'][$i]['description'] = '';
//$modversion['config'][$i]['formtype'] = 'textbox';
//$modversion['config'][$i]['valuetype'] = 'int';
//$modversion['config'][$i]['default'] = 640;
//$i++;
//$modversion['config'][$i]['name'] = 'tdmpicture_java_heigth';
//$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_JAVA_HEIGTH';
//$modversion['config'][$i]['description'] = '';
//$modversion['config'][$i]['formtype'] = 'textbox';
//$modversion['config'][$i]['valuetype'] = 'int';
//$modversion['config'][$i]['default'] = 400;
//$i++;
include_once XOOPS_ROOT_PATH . "/class/xoopslists.php";
$modversion["config"][$i]["name"]           = "tdmpicture_editor";
$modversion["config"][$i]["title"]          = "_MI_TDMPICTURE_EDITOR";
$modversion["config"][$i]["description"]    = "";
$modversion["config"][$i]["formtype"]       = "select";
$modversion["config"][$i]["valuetype"]      = "text";
$modversion["config"][$i]["default"]        = "dhtmltextarea";
$modversion["config"][$i]["options"]        = XoopsLists::getDirListAsArray(XOOPS_ROOT_PATH . "/class/xoopseditor");
$modversion["config"][$i]["category"]       = "global";
$i++;

$modversion['config'][$i]['name'] = 'tdmpicture_favourite';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_FAVOURITE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '10';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_page';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_PAGE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '10';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_width';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_WIDTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 600;
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_heigth';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_HEIGTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 400;
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_thumb_style';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_THUMB_STYLE';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'limit-width-height';
$modversion['config'][$i]['options'] = array(_MI_TDMPICTURE_THUMB_STYLE_CENTER => 'center', _MI_TDMPICTURE_THUMB_STYLE_HW => 'limit-width-height',  _MI_TDMPICTURE_THUMB_STYLE_W => 'limit-width',  _MI_TDMPICTURE_THUMB_STYLE_H => 'limit-height');
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_thumb_width';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_THUMB_WIDTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 150;
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_thumb_heigth';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_THUMB_HEIGTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 150;
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_thumb_quality';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_THUMB_QUALITY';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 75;
$i++;
//$modversion['config'][$i]['name'] = 'tdmpicture_thumb_deco';
//$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_THUMB_DECO';
//$modversion['config'][$i]['description'] = '';
//$modversion['config'][$i]['formtype'] = 'select';
//$modversion['config'][$i]['valuetype'] = 'text';
//$modversion['config'][$i]['default'] = 'paper-clip';
//$modversion['config'][$i]['options'] = array('paper-clip' => 'paper-clip', 'tape' => 'tape', 'pin' => 'pin', 'None' => 'None');
//$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_slide_width';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_SLIDE_WIDTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 600;
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_slide_height';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_SLIDE_HEIGTH';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 400;
$i++;
//$modversion['config'][$i]['name'] = 'tdmpicture_cat_cel';
//$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_CAT_CEL';
//$modversion['config'][$i]['description'] = '';
//$modversion['config'][$i]['formtype'] = 'textbox';
//$modversion['config'][$i]['valuetype'] = 'int';
//$modversion['config'][$i]['default'] = 2;
//$i++;
//$modversion['config'][$i]['name'] = 'tdmpicture_cat_souscel';
//$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_CAT_SOUSCEL';
//$modversion['config'][$i]['description'] = '';
//$modversion['config'][$i]['formtype'] = 'textbox';
//$modversion['config'][$i]['valuetype'] = 'int';
//$modversion['config'][$i]['default'] = 10;
//$i++;
//

$modversion['config'][$i]['name'] = 'tdmpicture_display';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_DISPLAY';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'display thumb_view';
$modversion['config'][$i]['options'] = array('minimal' => 'display thumb_view', 'full' => 'display');
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_social';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_SOCIAL';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_rss';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_RSS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_pdf';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_PDF';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_description';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_DESCRIPTION';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;
$modversion['config'][$i]['name'] = 'tdmpicture_keywords';
$modversion['config'][$i]['title'] = '_MI_TDMPICTURE_KEYWORDS';
$modversion['config'][$i]['description'] = '';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';
$i++;

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'st';
$modversion['comments']['pageName'] = 'viewfile.php';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'picture_comments_approve';
$modversion['comments']['callback']['update'] = 'picture_comments_update';

// Blocks
//*************************************************************
$i = 1;
$modversion['blocks'][$i]['file'] = "tdmpicture_minitable.php";
$modversion['blocks'][$i]['name'] = _AM_TDMPICTURE_BLOCK_DATE;
$modversion['blocks'][$i]['description'] = "";
$modversion['blocks'][$i]['show_func'] = "b_tdmpicture";
$modversion['blocks'][$i]['edit_func'] = "b_tdmpicture_edit";
$modversion['blocks'][$i]['options'] = "file_indate|10|50|5|30|30|0";
$modversion['blocks'][$i]['template'] = "tdmpicture_minitable.html";
$i++;
$modversion['blocks'][$i]['file'] = "tdmpicture_minitable.php";
$modversion['blocks'][$i]['name'] = _AM_TDMPICTURE_BLOCK_COUNTS;
$modversion['blocks'][$i]['description'] = "";
$modversion['blocks'][$i]['show_func'] = "b_tdmpicture";
$modversion['blocks'][$i]['edit_func'] = "b_tdmpicture_edit";
$modversion['blocks'][$i]['options'] = "file_counts|10|50|5|30|30|0";
$modversion['blocks'][$i]['template'] = "tdmpicture_minitable.html";
$i++;
$modversion['blocks'][$i]['file'] = "tdmpicture_minitable.php";
$modversion['blocks'][$i]['name'] = _AM_TDMPICTURE_BLOCK_HITS;
$modversion['blocks'][$i]['description'] = "";
$modversion['blocks'][$i]['show_func'] = "b_tdmpicture";
$modversion['blocks'][$i]['edit_func'] = "b_tdmpicture_edit";
$modversion['blocks'][$i]['options'] = "file_hits|10|50|5|30|30|0";
$modversion['blocks'][$i]['template'] = "tdmpicture_minitable.html";
$i++;
$modversion['blocks'][$i]['file'] = "tdmpicture_minitable.php";
$modversion['blocks'][$i]['name'] = _AM_TDMPICTURE_BLOCK_DL;
$modversion['blocks'][$i]['description'] = "";
$modversion['blocks'][$i]['show_func'] = "b_tdmpicture";
$modversion['blocks'][$i]['edit_func'] = "b_tdmpicture_edit";
$modversion['blocks'][$i]['options'] = "file_dl|10|50|5|30|30|0";
$modversion['blocks'][$i]['template'] = "tdmpicture_minitable.html";
$i++;
$modversion['blocks'][$i]['file'] = "tdmpicture_minitable.php";
$modversion['blocks'][$i]['name'] = _AM_TDMPICTURE_BLOCK_COMMENTS;
$modversion['blocks'][$i]['description'] = "";
$modversion['blocks'][$i]['show_func'] = "b_tdmpicture";
$modversion['blocks'][$i]['edit_func'] = "b_tdmpicture_edit";
$modversion['blocks'][$i]['options'] = "file_comments|10|50|5|30|30|0";
$modversion['blocks'][$i]['template'] = "tdmpicture_minitable.html";
$i++;
$modversion['blocks'][$i]['file'] = "tdmpicture_minitable.php";
$modversion['blocks'][$i]['name'] = _AM_TDMPICTURE_BLOCK_RANDS;
$modversion['blocks'][$i]['description'] = "";
$modversion['blocks'][$i]['show_func'] = "b_tdmpicture";
$modversion['blocks'][$i]['edit_func'] = "b_tdmpicture_edit";
$modversion['blocks'][$i]['options'] = "RAND()|10|50|5|30|30|0";
$modversion['blocks'][$i]['template'] = "tdmpicture_minitable.html";
$i++;

?>